/**
 * Socratic Rewind Types
 * For the "Socratic Rewind" feature that guides students back to their last valid step
 * after making an error, using the Socratic method.
 */

import type { Step } from './scaffold'
import type { ConstraintCollision, CollisionType } from './constraintCollision'

/**
 * The context needed to generate a Socratic Rewind response
 * Based on the three inputs from the system prompt:
 * 1. PREVIOUS_VALID_STEP: The last step the student got right
 * 2. CURRENT_ERROR: The incorrect step the student just attempted
 * 3. VIOLATED_PRINCIPLE: The physics law or mathematical rule that contradicts the error
 */
export interface SocraticRewindContext {
  previousValidStep: {
    stepId: number
    stepTitle: string
    stepContent: string // What the student did/agreed to in this step
    userAnswer?: string // Student's answer in this step
  }
  currentError: {
    stepId?: number
    description: string // What the student did wrong
    errorType: 'sign_convention' | 'vector_direction' | 'force_missing' | 'wrong_equation' |
               'unit_error' | 'constraint_violation' | 'algebra_error' | 'conceptual_gap' | 'other'
    studentInput?: string // The actual incorrect input from student
  }
  violatedPrinciple: {
    name: string // e.g., "Sign Convention", "Newton's Third Law"
    description: string // Explanation of the principle
    category: 'kinematics' | 'dynamics' | 'conservation' | 'vectors' | 'math' | 'constraints'
  }
  problemContext: {
    problemText: string
    domain: string
    subdomain: string
  }
}

/**
 * The response generated by the Socratic Rewind agent
 * Following the algorithm:
 * 1. The Stop - Pause for calibration
 * 2. The Rewind - Reference the previous valid step
 * 3. The Comparison - Ask student to compare steps
 * 4. The Bridge Question - Highlight the contradiction
 */
export interface SocraticRewindResponse {
  // The "Stop" message - frames the pause
  stopMessage: string

  // The "Rewind" reference - quotes the previous valid step
  rewindReference: {
    stepLabel: string // e.g., "Step 1", "Your FBD"
    quotedContent: string // What the student did/agreed to
  }

  // The "Comparison" prompt - asks student to look at both
  comparisonPrompt: string

  // The "Bridge Question" - single targeted question highlighting contradiction
  bridgeQuestion: string

  // Optional follow-up if student is still stuck
  gentleNudge?: string

  // Related concepts for review panel
  relatedConcepts?: string[]

  // Step to highlight in the UI (for visual navigation)
  highlightStepId?: number
}

/**
 * State of the Socratic Rewind modal
 */
export type SocraticRewindState =
  | 'idle' // No rewind active
  | 'triggered' // Rewind has been triggered, showing initial message
  | 'awaiting_acknowledgment' // Waiting for student to acknowledge the pause
  | 'showing_rewind' // Showing the previous valid step reference
  | 'showing_comparison' // Student is comparing steps
  | 'showing_bridge' // Showing the bridge question
  | 'resolved' // Student has acknowledged and is ready to proceed

/**
 * Trigger sources for the Socratic Rewind
 */
export type RewindTriggerSource =
  | 'sanity_check_failed' // From SanityCheckMatrix
  | 'grade_conceptual_gap' // From solution grading (CONCEPTUAL_GAP result)
  | 'constraint_collision' // From constraint collision detection
  | 'circuit_breaker' // From circuit breaker intervention
  | 'manual' // Manually triggered (for testing)

/**
 * Event logged when Socratic Rewind is used
 */
export interface SocraticRewindEvent {
  id: string
  timestamp: string
  problemId: string
  triggerSource: RewindTriggerSource
  context: SocraticRewindContext
  response?: SocraticRewindResponse
  studentInteraction: {
    timeToAcknowledge?: number // ms
    proceedClicked: boolean
    returnedToStep?: number
  }
  outcome: 'resolved' | 'dismissed' | 'escalated'
}

/**
 * Map error types to violated principle categories
 */
export const ERROR_TYPE_TO_PRINCIPLE_CATEGORY: Record<
  SocraticRewindContext['currentError']['errorType'],
  SocraticRewindContext['violatedPrinciple']['category']
> = {
  sign_convention: 'vectors',
  vector_direction: 'vectors',
  force_missing: 'dynamics',
  wrong_equation: 'math',
  unit_error: 'math',
  constraint_violation: 'constraints',
  algebra_error: 'math',
  conceptual_gap: 'dynamics',
  other: 'dynamics',
}

/**
 * Map collision types to error types
 */
export const COLLISION_TYPE_TO_ERROR_TYPE: Record<
  CollisionType,
  SocraticRewindContext['currentError']['errorType']
> = {
  OMISSION: 'force_missing',
  ADDITION: 'constraint_violation',
  REVERSAL: 'sign_convention',
  SUBSTITUTION: 'unit_error',
}

/**
 * Helper to build a rewind context from a constraint collision
 */
export function buildRewindContextFromCollision(
  collision: ConstraintCollision,
  previousStep: Step,
  previousStepAnswer: string | undefined,
  problemText: string,
  domain: string,
  subdomain: string
): SocraticRewindContext {
  const constraintDescription = 'description' in collision.problemConstraint
    ? collision.problemConstraint.description
    : collision.problemConstraint.rawText

  return {
    previousValidStep: {
      stepId: previousStep.id,
      stepTitle: previousStep.title,
      stepContent: previousStep.question || previousStep.title,
      userAnswer: previousStepAnswer,
    },
    currentError: {
      stepId: collision.affectedStepIds[0],
      description: collision.explanation,
      errorType: COLLISION_TYPE_TO_ERROR_TYPE[collision.collisionType],
      studentInput: collision.studentAssumption?.description,
    },
    violatedPrinciple: {
      name: constraintDescription,
      description: collision.explanation,
      category: 'constraints',
    },
    problemContext: {
      problemText,
      domain,
      subdomain,
    },
  }
}
