/**
 * Dual Hint Engine
 *
 * Routes hints based on step type:
 * - physics_concept: Socratic questions (no formula dumps)
 * - math_manipulation: Math-coach hints (identity reminders, algebra tips)
 * - diagram: Visualization-focused hints
 * - sanity_check: Physical intuition hints
 */

import type { StepType, HintLevel } from '@/types/scaffold'

/**
 * Hint style configuration for each step type
 */
export interface HintStyleConfig {
  icon: string
  headerText: string
  headerColor: string
  tipPrefix: string
}

export const HINT_STYLES: Record<StepType, HintStyleConfig> = {
  physics_concept: {
    icon: 'M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z',
    headerText: 'Think Conceptually',
    headerColor: 'text-blue-600 dark:text-blue-400',
    tipPrefix: 'Ask yourself:'
  },
  math_manipulation: {
    icon: 'M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z',
    headerText: 'Math Coach Tip',
    headerColor: 'text-purple-600 dark:text-purple-400',
    tipPrefix: 'Remember:'
  },
  diagram: {
    icon: 'M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z',
    headerText: 'Visualize It',
    headerColor: 'text-green-600 dark:text-green-400',
    tipPrefix: 'Picture this:'
  },
  sanity_check: {
    icon: 'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z',
    headerText: 'Check Your Work',
    headerColor: 'text-amber-600 dark:text-amber-400',
    tipPrefix: 'Consider:'
  }
}

/**
 * Math manipulation helper phrases
 */
export const MATH_COACH_TIPS = {
  algebra: [
    'Factor out common terms first',
    'Group similar variables together',
    'Try completing the square',
    'Look for difference of squares pattern'
  ],
  calculus: [
    'Chain rule: differentiate outer, then inner',
    'Integration by parts: choose u wisely',
    'Substitution often simplifies radicals',
    'Check limits of integration after substitution'
  ],
  trigonometry: [
    'sin²θ + cos²θ = 1 is your friend',
    'Double angle formulas can simplify',
    'Consider converting to exponentials',
    'Small angle approximation: sin θ ≈ θ for small θ'
  ],
  vectors: [
    'Dot product gives scalar, cross product gives vector',
    'Component form often simplifies calculations',
    'Check your sign conventions',
    'Unit vectors help normalize directions'
  ]
}

/**
 * Socratic prompts for physics concepts
 */
export const SOCRATIC_PROMPTS = {
  mechanics: [
    'What quantities are conserved here?',
    'In whose reference frame are you analyzing this?',
    'What forces are acting on the system?',
    'Where is the center of mass?'
  ],
  electromagnetism: [
    'What are the sources of the field?',
    'Is there any symmetry you can exploit?',
    'What boundary conditions apply?',
    'How does the field vary in space?'
  ],
  thermodynamics: [
    'Is this process reversible or irreversible?',
    'What state variables are changing?',
    'Is the system isolated, closed, or open?',
    'What does the first law tell you here?'
  ],
  waves: [
    'What type of wave is this?',
    'What boundary conditions exist?',
    'What is the relationship between frequency and wavelength?',
    'Is interference constructive or destructive?'
  ]
}

/**
 * Get the appropriate hint style for a step type
 */
export function getHintStyle(stepType?: StepType): HintStyleConfig {
  return HINT_STYLES[stepType || 'physics_concept']
}

/**
 * Format hint content based on step type
 * - For physics_concept: Ensures Socratic questioning style
 * - For math_manipulation: Adds math coach prefixes
 */
export function formatHintForStepType(
  hint: HintLevel,
  stepType?: StepType
): { formattedContent: string; style: HintStyleConfig } {
  const style = getHintStyle(stepType)

  // The content is already generated by the AI with the appropriate style
  // This function provides additional formatting context
  return {
    formattedContent: hint.content,
    style
  }
}

/**
 * Get a contextual tip based on step type and domain
 */
export function getContextualTip(
  stepType?: StepType,
  domain?: string
): string | null {
  if (!stepType) return null

  if (stepType === 'math_manipulation') {
    // Return a random math tip
    const categories = Object.values(MATH_COACH_TIPS)
    const allTips = categories.flat()
    return allTips[Math.floor(Math.random() * allTips.length)]
  }

  if (stepType === 'physics_concept' && domain) {
    // Return a domain-specific Socratic prompt
    const domainLower = domain.toLowerCase()
    if (domainLower.includes('mechanic')) {
      return SOCRATIC_PROMPTS.mechanics[Math.floor(Math.random() * SOCRATIC_PROMPTS.mechanics.length)]
    }
    if (domainLower.includes('electro') || domainLower.includes('magnet')) {
      return SOCRATIC_PROMPTS.electromagnetism[Math.floor(Math.random() * SOCRATIC_PROMPTS.electromagnetism.length)]
    }
    if (domainLower.includes('thermo')) {
      return SOCRATIC_PROMPTS.thermodynamics[Math.floor(Math.random() * SOCRATIC_PROMPTS.thermodynamics.length)]
    }
    if (domainLower.includes('wave') || domainLower.includes('optic')) {
      return SOCRATIC_PROMPTS.waves[Math.floor(Math.random() * SOCRATIC_PROMPTS.waves.length)]
    }
  }

  return null
}

/**
 * Get the step type badge/label for UI display
 */
export function getStepTypeBadge(stepType?: StepType): {
  label: string
  bgClass: string
  textClass: string
} {
  switch (stepType) {
    case 'physics_concept':
      return {
        label: 'Physics',
        bgClass: 'bg-blue-100 dark:bg-blue-900/30',
        textClass: 'text-blue-700 dark:text-blue-300'
      }
    case 'math_manipulation':
      return {
        label: 'Math',
        bgClass: 'bg-purple-100 dark:bg-purple-900/30',
        textClass: 'text-purple-700 dark:text-purple-300'
      }
    case 'diagram':
      return {
        label: 'Diagram',
        bgClass: 'bg-green-100 dark:bg-green-900/30',
        textClass: 'text-green-700 dark:text-green-300'
      }
    case 'sanity_check':
      return {
        label: 'Check',
        bgClass: 'bg-amber-100 dark:bg-amber-900/30',
        textClass: 'text-amber-700 dark:text-amber-300'
      }
    default:
      return {
        label: 'Step',
        bgClass: 'bg-gray-100 dark:bg-gray-800',
        textClass: 'text-gray-700 dark:text-gray-300'
      }
  }
}

// ============================================
// Validation Error Feedback Messages
// ============================================

export type ErrorCategory = 'physics' | 'math' | 'conceptual' | 'procedural'

export interface ValidationFeedback {
  category: ErrorCategory
  label: string
  shortTip: string
  encouragement: string
  icon: string
  bgClass: string
  textClass: string
  borderClass: string
}

/**
 * Physics-focused error feedback messages
 */
const PHYSICS_ERROR_FEEDBACK: ValidationFeedback = {
  category: 'physics',
  label: 'Physics Understanding',
  shortTip: 'The physics concept needs review',
  encouragement: 'The math looks fine - focus on understanding the physical principles involved.',
  icon: 'M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z',
  bgClass: 'bg-blue-500/10 dark:bg-blue-500/20',
  textClass: 'text-blue-700 dark:text-blue-300',
  borderClass: 'border-blue-500/30 dark:border-blue-500/50'
}

/**
 * Math-focused error feedback messages
 */
const MATH_ERROR_FEEDBACK: ValidationFeedback = {
  category: 'math',
  label: 'Mathematical Execution',
  shortTip: 'Check your algebra or arithmetic',
  encouragement: 'You understood the physics correctly! Just fix the calculation and you\'ll have it.',
  icon: 'M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z',
  bgClass: 'bg-purple-500/10 dark:bg-purple-500/20',
  textClass: 'text-purple-700 dark:text-purple-300',
  borderClass: 'border-purple-500/30 dark:border-purple-500/50'
}

/**
 * Conceptual error feedback (mixed physics + approach)
 */
const CONCEPTUAL_ERROR_FEEDBACK: ValidationFeedback = {
  category: 'conceptual',
  label: 'Approach Issue',
  shortTip: 'Consider a different problem-solving strategy',
  encouragement: 'Let\'s step back and think about the right approach for this problem.',
  icon: 'M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z',
  bgClass: 'bg-amber-500/10 dark:bg-amber-500/20',
  textClass: 'text-amber-700 dark:text-amber-300',
  borderClass: 'border-amber-500/30 dark:border-amber-500/50'
}

/**
 * Procedural error feedback (minor slips)
 */
const PROCEDURAL_ERROR_FEEDBACK: ValidationFeedback = {
  category: 'procedural',
  label: 'Minor Slip',
  shortTip: 'Small error in execution',
  encouragement: 'Almost there! Just a small fix needed.',
  icon: 'M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z',
  bgClass: 'bg-amber-500/10 dark:bg-amber-500/20',
  textClass: 'text-amber-700 dark:text-amber-300',
  borderClass: 'border-amber-500/30 dark:border-amber-500/50'
}

/**
 * Get validation feedback based on physics vs math correctness
 */
export function getValidationFeedback(
  physicsCorrect: boolean,
  mathCorrect: boolean,
  errorTypes?: Array<{ type: string }>
): ValidationFeedback {
  // Analyze error types if provided
  if (errorTypes && errorTypes.length > 0) {
    const hasPhysicsError = errorTypes.some(e =>
      ['concept', 'approach'].includes(e.type)
    )
    const hasMathError = errorTypes.some(e =>
      ['sign', 'algebra', 'units'].includes(e.type)
    )

    if (hasPhysicsError && !hasMathError) {
      return PHYSICS_ERROR_FEEDBACK
    }
    if (hasMathError && !hasPhysicsError) {
      return MATH_ERROR_FEEDBACK
    }
  }

  // Fall back to physics/math correctness flags
  if (!physicsCorrect && mathCorrect) {
    return PHYSICS_ERROR_FEEDBACK
  }

  if (physicsCorrect && !mathCorrect) {
    return MATH_ERROR_FEEDBACK
  }

  if (!physicsCorrect && !mathCorrect) {
    return CONCEPTUAL_ERROR_FEEDBACK
  }

  // Both correct but some minor issue
  return PROCEDURAL_ERROR_FEEDBACK
}

/**
 * Get specific math error messages based on error type
 */
export function getMathErrorMessage(errorType: string): string {
  switch (errorType) {
    case 'sign':
      return 'Check your sign conventions - a negative might be missing or misplaced.'
    case 'algebra':
      return 'Review your algebraic manipulation - there may be a factoring or simplification error.'
    case 'units':
      return 'Verify your unit conversions - make sure all quantities are in consistent units.'
    default:
      return 'Double-check your calculations step by step.'
  }
}

/**
 * Get specific physics error messages based on error type
 */
export function getPhysicsErrorMessage(errorType: string): string {
  switch (errorType) {
    case 'concept':
      return 'The underlying physics principle may need reconsideration.'
    case 'approach':
      return 'Consider whether a different method (energy, momentum, forces) might be more appropriate.'
    default:
      return 'Review the physical situation and the principles that govern it.'
  }
}
